// Generated by Wrangler on Tue Mar 11 2025 12:27:31 GMT-0700 (Mountain Standard Time)
// by running `wrangler types`

interface Env {
	DATABASE: "DB";
	ADMIN_KEY: "9jjd548v5zd7o68o2jv540so";
	HONEYBADGER_API_KEY: "hbp_JaeogAzEIKRn5HJkUMpPEljzBracoA1ooE6t";
	HONEYBADGER_ENV: "production";
	DB: D1Database;
}
